Python 3.5.1 compatibilty
Better compatibility with the current ConfigParser interface to avoid `TypeError: get() got an unexpected keyword argument 'raw'` after http://bugs.python.org/issue21159 introduced in Python 3.5.1.